name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Esto le da permiso de crear el archivo de descarga
    steps:
      - uses: actions/checkout@v4 # Versión actualizada

      - name: Setup Python
        uses: actions/setup-python@v5 # Versión actualizada
        with:
          python-version: '3.11'

      - name: Install Flet and Dependencies
        run: |
          pip install flet
          # Esto instala herramientas necesarias para compilar en Linux
          sudo apt-get update
          sudo apt-get install -y dep-tooling 

      - name: Setup Java
        uses: actions/setup-java@v4 # Versión actualizada
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: flet build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: swiftie-app-apk
          path: build/flutter/outputs/flutter-apk/app-release.apk
